"""initial schema

Revision ID: b5b02bc9d209
Revises: 
Create Date: 2026-06-16 18:15:51.766839

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5b02bc9d209'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('provider_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('api_key_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_profiles_kind_is_default', 'provider_profiles', ['kind', 'is_default'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_chat_profile_id', sa.UUID(), nullable=True),
    sa.Column('default_embedding_profile_id', sa.UUID(), nullable=True),
    sa.Column('default_reranker_profile_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_chat_profile_id'], ['provider_profiles.id'], ),
    sa.ForeignKeyConstraint(['default_embedding_profile_id'], ['provider_profiles.id'], ),
    sa.ForeignKeyConstraint(['default_reranker_profile_id'], ['provider_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_default_chat_profile_id'), 'chats', ['default_chat_profile_id'], unique=False)
    op.create_index(op.f('ix_chats_default_embedding_profile_id'), 'chats', ['default_embedding_profile_id'], unique=False)
    op.create_index(op.f('ix_chats_default_reranker_profile_id'), 'chats', ['default_reranker_profile_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_chat_id'), 'documents', ['chat_id'], unique=False)
    op.create_index('ix_documents_chat_status', 'documents', ['chat_id', 'status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('chat_profile_id', sa.UUID(), nullable=True),
    sa.Column('selected_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('document_scope_locked', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_profile_id'], ['provider_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_chat_id'), 'sessions', ['chat_id'], unique=False)
    op.create_index(op.f('ix_sessions_chat_profile_id'), 'sessions', ['chat_profile_id'], unique=False)
    op.create_table('chat_documents',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'document_id')
    )
    op.create_table('document_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('node_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_nodes_chat_id'), 'document_nodes', ['chat_id'], unique=False)
    op.create_index('ix_document_nodes_doc_order', 'document_nodes', ['document_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_document_nodes_document_id'), 'document_nodes', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_nodes_parent_id'), 'document_nodes', ['parent_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_chat_id'), 'ingestion_jobs', ['chat_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_document_id'), 'ingestion_jobs', ['document_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('structured_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('context_excerpt', sa.Text(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['document_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_structured_facts_chat_document', 'structured_facts', ['chat_id', 'document_id'], unique=False)
    op.create_index(op.f('ix_structured_facts_chat_id'), 'structured_facts', ['chat_id'], unique=False)
    op.create_index('ix_structured_facts_chat_kind', 'structured_facts', ['chat_id', 'kind'], unique=False)
    op.create_index(op.f('ix_structured_facts_document_id'), 'structured_facts', ['document_id'], unique=False)
    op.create_index(op.f('ix_structured_facts_source_node_id'), 'structured_facts', ['source_node_id'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['document_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_summaries_chat_document', 'summaries', ['chat_id', 'document_id'], unique=False)
    op.create_index(op.f('ix_summaries_chat_id'), 'summaries', ['chat_id'], unique=False)
    op.create_index(op.f('ix_summaries_document_id'), 'summaries', ['document_id'], unique=False)
    op.create_index(op.f('ix_summaries_source_node_id'), 'summaries', ['source_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summaries_source_node_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_document_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_chat_id'), table_name='summaries')
    op.drop_index('ix_summaries_chat_document', table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_structured_facts_source_node_id'), table_name='structured_facts')
    op.drop_index(op.f('ix_structured_facts_document_id'), table_name='structured_facts')
    op.drop_index('ix_structured_facts_chat_kind', table_name='structured_facts')
    op.drop_index(op.f('ix_structured_facts_chat_id'), table_name='structured_facts')
    op.drop_index('ix_structured_facts_chat_document', table_name='structured_facts')
    op.drop_table('structured_facts')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_ingestion_jobs_document_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_chat_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_document_nodes_parent_id'), table_name='document_nodes')
    op.drop_index(op.f('ix_document_nodes_document_id'), table_name='document_nodes')
    op.drop_index('ix_document_nodes_doc_order', table_name='document_nodes')
    op.drop_index(op.f('ix_document_nodes_chat_id'), table_name='document_nodes')
    op.drop_table('document_nodes')
    op.drop_table('chat_documents')
    op.drop_index(op.f('ix_sessions_chat_profile_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_chat_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_documents_chat_status', table_name='documents')
    op.drop_index(op.f('ix_documents_chat_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chats_default_reranker_profile_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_default_embedding_profile_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_default_chat_profile_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index('ix_provider_profiles_kind_is_default', table_name='provider_profiles')
    op.drop_table('provider_profiles')
    # ### end Alembic commands ###
