"""Application-level encryption and secret masking utilities.

Security contract
-----------------
- ``encrypt`` / ``decrypt`` use Fernet symmetric encryption (AES-128-CBC +
  HMAC-SHA256).  The ``app_encryption_key`` setting must be a base64-url
  encoded 32-byte key (see ``generate_key()`` or ``Fernet.generate_key()``).
- ``mask_secret`` is used by **all** log statements that involve credentials.
  It MUST be called before any credential reaches a logger.
- This module MUST NOT log the plaintext of any secret itself.

Usage
-----
    from app.security import encrypt, decrypt, mask_secret

    token = encrypt("sk-my-openai-key")   # bytes
    plain = decrypt(token)                 # "sk-my-openai-key"
    masked = mask_secret("sk-my-openai-key")  # "sk-...key"
"""

from __future__ import annotations

import base64
import hashlib
import logging

from cryptography.fernet import Fernet, InvalidToken

from app.config import get_settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _get_fernet() -> Fernet:
    """Build a ``Fernet`` instance from ``settings.app_encryption_key``.

    The key may be provided in two formats:
    - A 32-byte base64-url string as generated by ``Fernet.generate_key()``.
    - Any other string, in which case we derive a valid 32-byte Fernet key
      via SHA-256 to tolerate human-readable env-var values (e.g., tests).

    The derivation is deterministic and repeatable for the same input string.
    """
    raw_key = get_settings().app_encryption_key.encode()
    # Try using it directly (32 bytes base64 → 44 chars, must decode to 32 bytes)
    try:
        decoded = base64.urlsafe_b64decode(raw_key + b"==")
        if len(decoded) == 32:
            return Fernet(raw_key)
    except Exception:
        pass
    # Fall back to SHA-256 derivation → exactly 32 bytes → base64-url encode
    derived = hashlib.sha256(raw_key).digest()
    fernet_key = base64.urlsafe_b64encode(derived)
    return Fernet(fernet_key)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def encrypt(plaintext: str) -> bytes:
    """Encrypt *plaintext* with Fernet (AES-128-CBC + HMAC) and return token bytes.

    Parameters
    ----------
    plaintext:
        The secret string to encrypt (e.g., an API key).

    Returns
    -------
    bytes
        The Fernet token (base64-url encoded, safe to store as-is).
    """
    return _get_fernet().encrypt(plaintext.encode())


def decrypt(token: bytes) -> str:
    """Decrypt a Fernet *token* and return the plaintext string.

    Parameters
    ----------
    token:
        Bytes returned by a previous call to ``encrypt()``.

    Raises
    ------
    cryptography.fernet.InvalidToken
        If the token is invalid or was encrypted with a different key.
    """
    try:
        return _get_fernet().decrypt(token).decode()
    except InvalidToken:
        # Log *without* revealing the token value
        logger.error("Failed to decrypt token (InvalidToken) — key mismatch or corruption")
        raise


def mask_secret(value: str | None) -> str:
    """Return a masked representation of *value* safe for logging.

    Rules
    -----
    - ``None``     → ``""``
    - len ≤ 8      → ``"***"`` (too short to show partial)
    - len 9–12     → show first 2 + ``"..."`` + last 2  (e.g. ``"sk...ey"``)
    - len > 12     → show first 3 + ``"..."`` + last 4  (e.g. ``"sk-...7890"``)

    The result **never** contains the full secret.

    Examples
    --------
    >>> mask_secret("sk-abcdef1234567890")
    'sk-...7890'
    >>> mask_secret(None)
    ''
    >>> mask_secret("short")
    '***'
    """
    if value is None:
        return ""
    n = len(value)
    if n <= 8:
        return "***"
    if n <= 12:
        return f"{value[:2]}...{value[-2:]}"
    return f"{value[:3]}...{value[-4:]}"


def generate_key() -> str:
    """Generate a fresh Fernet-compatible 32-byte key (base64-url encoded).

    This is a convenience helper for initial deployment setup.  The output
    should be stored as ``APP_ENCRYPTION_KEY`` in the environment.

    Returns
    -------
    str
        A 44-character URL-safe base64 string.
    """
    return Fernet.generate_key().decode()
