"""Unit tests for ``app.vespa.app_package``.

All tests are deterministic and have NO external dependencies (no Vespa,
no network, no sleep).

Coverage:
- ``build_application_package(dim)`` returns a valid ``ApplicationPackage``
  with the correct schema name, all required fields, and all 5 rank profiles.
- The embedding tensor type string reflects the supplied ``embedding_dim``.
- All 14 ``source_type`` values are covered by the boost map (or have a
  default fallback of 1.0 built into the expression).
- ``write_application_files(tmp_path, dim)`` creates ``schemas/document_chunk.sd``
  on disk containing ``tensor<float>(x[DIM])``.
- ``services.xml`` generated by ``write_application_files`` contains the
  correct container id (``default``) and content cluster id (``documents``).
- ``hosts.xml`` contains the ``node1`` alias.
- ``validation-overrides.xml`` contains the required validation IDs.
"""

from __future__ import annotations

import pytest

from app.vespa.app_package import (
    SOURCE_TYPE_BOOST,
    SOURCE_TYPES,
    build_application_package,
    write_application_files,
)

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

DEFAULT_DIM = 1024


@pytest.fixture(scope="module")
def pkg_1024():
    """Build once; reused across tests in this module."""
    return build_application_package(DEFAULT_DIM)


@pytest.fixture(scope="module")
def schema_1024(pkg_1024):
    return pkg_1024.schema


# ---------------------------------------------------------------------------
# ApplicationPackage basics
# ---------------------------------------------------------------------------


def test_package_name(pkg_1024):
    assert pkg_1024.name == "documentchunk"


def test_schema_name(schema_1024):
    assert schema_1024.name == "document_chunk"


# ---------------------------------------------------------------------------
# Required fields present
# ---------------------------------------------------------------------------

REQUIRED_FIELDS = [
    "vespa_document_id",
    "chat_id",
    "document_id",
    "source_node_id",
    "parent_node_id",
    "source_type",
    "title",
    "heading_path",
    "content",
    "keywords",
    "technical_keywords",
    "entities",
    "page_start",
    "page_end",
    "order_index",
    "token_count",
    "embedding",
    "created_at",
]


def test_all_required_fields_present(schema_1024):
    field_names = {f.name for f in schema_1024.document.fields}
    missing = set(REQUIRED_FIELDS) - field_names
    assert not missing, f"Missing fields: {missing}"


# ---------------------------------------------------------------------------
# Embedding tensor type
# ---------------------------------------------------------------------------


def test_embedding_tensor_type_default(schema_1024):
    emb_field = next(f for f in schema_1024.document.fields if f.name == "embedding")
    assert emb_field.type == "tensor<float>(x[1024])"


def test_embedding_tensor_type_custom_dim():
    pkg_512 = build_application_package(512)
    emb_field = next(
        f for f in pkg_512.schema.document.fields if f.name == "embedding"
    )
    assert emb_field.type == "tensor<float>(x[512])"
    # Changing dim changes the type string
    pkg_768 = build_application_package(768)
    emb_field_768 = next(
        f for f in pkg_768.schema.document.fields if f.name == "embedding"
    )
    assert emb_field_768.type == "tensor<float>(x[768])"


# ---------------------------------------------------------------------------
# Rank profiles
# ---------------------------------------------------------------------------

REQUIRED_RANK_PROFILES = [
    "bm25_only",
    "semantic_only",
    "hybrid_first_phase",
    "hybrid_with_native_rerank",
    "hybrid_for_cross_encoder",
]


def test_all_rank_profiles_present(schema_1024):
    profile_names = list(schema_1024.rank_profiles.keys())
    for name in REQUIRED_RANK_PROFILES:
        assert name in profile_names, f"Missing rank profile: {name!r}"


def test_bm25_only_has_no_vector_first_phase(schema_1024):
    rp = schema_1024.rank_profiles["bm25_only"]
    # first_phase should reference bm25(…) but NOT closeness
    expr = str(rp.first_phase)
    assert "bm25" in expr
    assert "closeness" not in expr


def test_semantic_only_first_phase(schema_1024):
    rp = schema_1024.rank_profiles["semantic_only"]
    expr = str(rp.first_phase)
    assert "closeness" in expr
    # No bm25 in first_phase expression (bm25 may appear in functions only)
    assert "bm25" not in expr


def test_hybrid_profiles_have_vector_in_first_phase(schema_1024):
    for name in ("hybrid_first_phase", "hybrid_for_cross_encoder"):
        rp = schema_1024.rank_profiles[name]
        expr = str(rp.first_phase)
        assert "closeness" in expr, f"{name} first_phase should include closeness"
        assert "bm25" in expr, f"{name} first_phase should include bm25"


def test_hybrid_with_native_rerank_has_second_phase(schema_1024):
    rp = schema_1024.rank_profiles["hybrid_with_native_rerank"]
    assert rp.second_phase is not None, "hybrid_with_native_rerank must have a second_phase"


def test_hybrid_for_cross_encoder_no_second_phase(schema_1024):
    rp = schema_1024.rank_profiles["hybrid_for_cross_encoder"]
    assert rp.second_phase is None, "hybrid_for_cross_encoder must NOT have a second_phase"


def test_rank_profiles_expose_match_features(schema_1024):
    for name in REQUIRED_RANK_PROFILES:
        rp = schema_1024.rank_profiles[name]
        assert rp.match_features, f"{name} must declare match_features"
        feature_strs = [str(f) for f in rp.match_features]
        assert any("bm25" in f for f in feature_strs), (
            f"{name} match_features must include a bm25 feature"
        )
        assert any("closeness" in f for f in feature_strs), (
            f"{name} match_features must include closeness"
        )


# ---------------------------------------------------------------------------
# source_type enumeration + boost map
# ---------------------------------------------------------------------------


def test_source_types_count():
    """There must be exactly 14 source types per CLAUDE.md §5.2."""
    assert len(SOURCE_TYPES) == 14, f"Expected 14 source types, got {len(SOURCE_TYPES)}"


def test_source_type_boost_covers_all_types_or_has_default():
    """Every SOURCE_TYPE must be in SOURCE_TYPE_BOOST or the expression has a
    numeric default fallback (which it always does — the expression ends
    with ``1.0``).  Also verify every explicitly boosted type is in
    SOURCE_TYPES.
    """
    for stype in SOURCE_TYPES:
        # Either explicitly listed or the default 1.0 fallback applies.
        weight = SOURCE_TYPE_BOOST.get(stype, 1.0)
        assert isinstance(weight, (int, float)), (
            f"Boost weight for {stype!r} must be numeric, got {weight!r}"
        )
        assert weight > 0, f"Boost weight for {stype!r} must be positive"


def test_source_type_boost_expression_contains_all_boost_entries(schema_1024):
    """The ``source_type_boost`` function in hybrid_first_phase must reference
    every key in ``SOURCE_TYPE_BOOST``."""
    rp = schema_1024.rank_profiles["hybrid_first_phase"]
    fn_map = {fn.name: fn for fn in (rp.functions or [])}
    assert "source_type_boost" in fn_map, "hybrid_first_phase must have source_type_boost function"
    expr = str(fn_map["source_type_boost"].expression)
    for stype in SOURCE_TYPE_BOOST:
        assert stype in expr, (
            f"source_type_boost expression missing entry for {stype!r}"
        )


# ---------------------------------------------------------------------------
# to_files / write_application_files — disk output
# ---------------------------------------------------------------------------


def test_write_application_files_creates_sd(tmp_path):
    """``write_application_files`` must create a ``document_chunk.sd`` file."""
    write_application_files(tmp_path, embedding_dim=1024)
    sd = tmp_path / "schemas" / "document_chunk.sd"
    assert sd.exists(), "schemas/document_chunk.sd must exist after write_application_files"


def test_sd_contains_correct_tensor_type(tmp_path):
    write_application_files(tmp_path, embedding_dim=1024)
    sd = tmp_path / "schemas" / "document_chunk.sd"
    content = sd.read_text()
    assert "tensor<float>(x[1024])" in content


def test_sd_tensor_type_changes_with_dim(tmp_path):
    d256 = tmp_path / "dim256"
    write_application_files(d256, embedding_dim=256)
    sd_content = (d256 / "schemas" / "document_chunk.sd").read_text()
    assert "tensor<float>(x[256])" in sd_content
    assert "tensor<float>(x[1024])" not in sd_content


def test_sd_contains_all_rank_profile_names(tmp_path):
    write_application_files(tmp_path, embedding_dim=1024)
    sd = tmp_path / "schemas" / "document_chunk.sd"
    content = sd.read_text()
    for name in REQUIRED_RANK_PROFILES:
        assert name in content, f"Rank profile {name!r} not found in document_chunk.sd"


def test_services_xml_created(tmp_path):
    write_application_files(tmp_path, embedding_dim=1024)
    svc = tmp_path / "services.xml"
    assert svc.exists()
    content = svc.read_text()
    assert 'id="default"' in content
    assert 'id="documents"' in content


def test_services_xml_query_timeout(tmp_path):
    write_application_files(tmp_path, embedding_dim=1024)
    content = (tmp_path / "services.xml").read_text()
    assert "5.0" in content or "5s" in content or "query-timeout" in content


def test_hosts_xml_created(tmp_path):
    write_application_files(tmp_path, embedding_dim=1024)
    hosts = tmp_path / "hosts.xml"
    assert hosts.exists()
    content = hosts.read_text()
    assert "node1" in content
    assert "localhost" in content


def test_validation_overrides_xml_created(tmp_path):
    write_application_files(tmp_path, embedding_dim=1024, validation_until="2026-12-31")
    vo = tmp_path / "validation-overrides.xml"
    assert vo.exists()
    content = vo.read_text()
    assert "tensor-type-change" in content
    assert "field-type-change" in content
    assert "indexing-change" in content
    assert "2026-12-31" in content


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------


def test_negative_embedding_dim_raises():
    with pytest.raises(ValueError, match="embedding_dim must be positive"):
        build_application_package(-1)


def test_zero_embedding_dim_raises():
    with pytest.raises(ValueError, match="embedding_dim must be positive"):
        build_application_package(0)
